POST {{api_url}}/api/v1/bucket/create

> {%
    client.global.set("bucketId", response.body.bucketId)
 %}

###
GET {{api_url}}/api/v1/bucket/all-events/{{bucketId}}
Accept: application/json

###
POST {{api_url}}/api/v1/bucket/transfer
Content-Type: application/json

{
  "bucketId": "{{bucketId}}",
  "amount": 15000.0
}

###
GET {{api_url}}/api/v1/bucket/current-balance/{{bucketId}}
Accept: application/json